version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: ./Docker/DockerfileService
    ports:
      - "50051:50051"
    depends_on: [db]


  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urls
    ports:
      - "5432:5432"
